name: Make and Publish to Github

on:
  push:
    tags:
      - "*"

env:
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: build distributable
        run: npm run make
      - uses: actions/upload-artifact@v4
        with:
          name: yt-trimmer-${{ github.ref_name }}-linux
          path: out/make/deb/x64/*.deb
      - uses: actions/upload-artifact@v4
        with:
          name: yt-trimmer-zip-${{ github.ref_name }}-linux
          path: out/make/zip/linux/x64/*.zip

  build-on-win:
    runs-on: windows-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run Workflow
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "cert.pfx"
          fileDir: "./"
          encodedString: ${{ secrets.BASE64_CERTIFICATE }}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: build distributable
        run: npm run make
        env:
          CERTIFICATE_PATH: ${{ steps.write_file.outputs.filePath }}
      - uses: actions/upload-artifact@v4
        with:
          name: yt-trimmer-${{ github.ref_name }}-windows
          path: out/make/squirrel.windows/x64
      - uses: actions/upload-artifact@v4
        with:
          name: yt-trimmer-zip-${{ github.ref_name }}-windows
          path: out/make/zip/win32/x64/*.zip
