name: Make and Publish to Github

on:
  push:
    branches:
      - main

env:
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  check-version:
    uses: ./.github/workflows/check-version.yaml
  build-on-linux:
    needs: check-version
    if: needs.check-version.outputs.SHOULD_PUBLISH == 'true'
    runs-on: windows-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: build distributable
        run: npm run make
      - uses: actions/upload-artifact@v4
        with:
          name: yt-trimmer-v${{needs.check-version.outputs.VERSION}}-linux
          path: out/make/deb/x64/*.deb
      - uses: actions/upload-artifact@v4
        with:
          name: yt-trimmer-zip-v${{needs.check-version.outputs.VERSION}}-linux
          path: out/make/zip/linux/x64/*.zip

  build-on-win:
    needs: check-version
    if: needs.check-version.outputs.SHOULD_PUBLISH == 'true'
    runs-on: windows-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: build distributable
        run: npm run make
      - uses: actions/upload-artifact@v4
        with:
          name: yt-trimmer-v${{needs.check-version.outputs.VERSION}}-windows
          path: out/make/squirrel.windows/x64
      - uses: actions/upload-artifact@v4
        with:
          name: yt-trimmer-zip-v${{needs.check-version.outputs.VERSION}}-windows
          path: out/make/zip/win32/x64/*.zip
